global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wdp-backend'
    static_configs:
      - targets: ['wdp-backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['wdp-alertmanager:9093']